# PyTorch 中的数据读取

## Dataset 类
```
继承 Dataset 类时，至少需要重写以下几个方法：_
_init__()：构造函数，可自定义数据读取方法以及进行数据预处理；
__len__()：返回数据集大小；
__getitem__()：索引数据集中的某一个数据。
```

In [1]:

import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    # 构造函数
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor
    # 返回数据集大小
    def __len__(self):
        return self.data_tensor.size(0)
    # 返回索引的数据与标签
    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]

In [4]:

# 生成数据
data_tensor = torch.randn(10, 3)
print(data_tensor)
target_tensor = torch.randint(2, (10,)) # 标签是0或1
print(target_tensor)
# 将数据封装成Dataset
my_dataset = MyDataset(data_tensor, target_tensor)

# 查看数据集大小
print('Dataset size:', len(my_dataset))
'''
输出：
Dataset size: 10
'''

# 使用索引调用数据
print('tensor_data[0]: ', my_dataset[0])
'''
输出:
tensor_data[0]:  (tensor([ 0.4931, -0.0697,  0.4171]), tensor(0))
'''

tensor([[-0.9849, -0.0599, -0.9594],
        [ 0.3254, -0.5734,  0.8641],
        [-0.9356, -1.1406,  1.0723],
        [-0.4413,  1.2660,  1.4593],
        [-1.2774, -0.7374, -1.0824],
        [ 0.5354,  0.0068,  1.2872],
        [ 0.1782, -2.4065, -0.1798],
        [-0.9404,  0.9411, -0.3518],
        [ 1.6631,  0.3896, -0.1946],
        [-0.7375, -0.3674,  0.0832]])
tensor([0, 0, 0, 0, 0, 0, 1, 1, 0, 1])
Dataset size: 10
tensor_data[0]:  (tensor([-0.9849, -0.0599, -0.9594]), tensor(0))


'\n输出:\ntensor_data[0]:  (tensor([ 0.4931, -0.0697,  0.4171]), tensor(0))\n'

## DataLoader 类

### 背景
    在实际项目中，如果数据量很大，考虑到内存有限、I/O 速度等问题，在训练过程中不可能一次性的将所有数据全部加载到内存中，
    也不能只用一个进程去加载，所以就需要多进程、迭代加载，而 DataLoader 就是基于这些需要被设计出来的。
    
    DataLoader 是一个迭代器，最基本的使用方法就是传入一个 Dataset 对象，它会根据参数 batch_size 的值生成一个 batch 的数据，节省内存的同时，它还可以实现多进程、数据打乱等处理。
    


In [5]:

from torch.utils.data import DataLoader
tensor_dataloader = DataLoader(dataset=my_dataset, # 传入的数据集, 必须参数
                               batch_size=2,       # 输出的batch大小
                               shuffle=True,       # 数据是否打乱
                               num_workers=0)      # 进程数, 0表示只有主进程

# 以循环形式输出
for data, target in tensor_dataloader: 
    print(data, target)
'''
输出:
tensor([[-0.1781, -1.1019, -0.1507],
        [-0.6170,  0.2366,  0.1006]]) tensor([0, 0])
tensor([[ 0.9451, -0.4923, -1.8178],
        [-0.4046, -0.5436, -1.7911]]) tensor([0, 0])
tensor([[-0.4561, -1.2480, -0.3051],
        [-0.9738,  0.9465,  0.4812]]) tensor([1, 0])
tensor([[ 0.0260,  1.5276,  0.1687],
        [ 1.3692, -0.0170, -1.6831]]) tensor([1, 0])
tensor([[ 0.0515, -0.8892, -0.1699],
        [ 0.4931, -0.0697,  0.4171]]) tensor([1, 0])
'''
 
# 输出一个batch
print('One batch tensor data: ', iter(tensor_dataloader).next())
'''
输出:
One batch tensor data:  [tensor([[ 0.9451, -0.4923, -1.8178],
        [-0.4046, -0.5436, -1.7911]]), tensor([0, 0])]
'''

tensor([[-0.9404,  0.9411, -0.3518],
        [-1.2774, -0.7374, -1.0824]]) tensor([1, 0])
tensor([[ 1.6631,  0.3896, -0.1946],
        [-0.4413,  1.2660,  1.4593]]) tensor([0, 0])
tensor([[ 0.3254, -0.5734,  0.8641],
        [-0.9356, -1.1406,  1.0723]]) tensor([0, 0])
tensor([[ 0.5354,  0.0068,  1.2872],
        [-0.7375, -0.3674,  0.0832]]) tensor([0, 1])
tensor([[ 0.1782, -2.4065, -0.1798],
        [-0.9849, -0.0599, -0.9594]]) tensor([1, 0])
One batch tensor data:  [tensor([[-0.9356, -1.1406,  1.0723],
        [ 0.5354,  0.0068,  1.2872]]), tensor([0, 0])]


'\n输出:\nOne batch tensor data:  [tensor([[ 0.9451, -0.4923, -1.8178],\n        [-0.4046, -0.5436, -1.7911]]), tensor([0, 0])]\n'

In [7]:
help(torch.utils.data.dataloader)

Help on module torch.utils.data.dataloader in torch.utils.data:

NAME
    torch.utils.data.dataloader - Definition of the DataLoader and associated iterators that subclass _BaseDataLoaderIter

DESCRIPTION
    To support these two classes, in `./_utils` we define many utility methods and
    functions to be run in multiprocessing. E.g., the data loading worker loop is
    in `./_utils/worker.py`.

CLASSES
    typing.Generic(builtins.object)
        DataLoader
    
    class DataLoader(typing.Generic)
     |  DataLoader(*args, **kwds)
     |  
     |  Data loader. Combines a dataset and a sampler, and provides an iterable over
     |  the given dataset.
     |  
     |  The :class:`~torch.utils.data.DataLoader` supports both map-style and
     |  iterable-style datasets with single- or multi-process loading, customizing
     |  loading order and optional automatic batching (collation) and memory pinning.
     |  
     |  See :py:mod:`torch.utils.data` documentation page for more details.

* 结合代码，我们梳理一下 DataLoader 中的几个参数，它们分别表示：

     * dataset：Dataset 类型，输入的数据集，必须参数；
     * batch_size：int 类型，每个 batch 有多少个样本；
     * shuffle：bool 类型，在每个 epoch 开始的时候，是否对数据进行重新打乱；
     * num_workers：int 类型，加载数据的进程数，0 意味着所有的数据都会被加载进主进程，默认为 0。

# 什么是 Torchvision

    yTroch 官方为我们提供了一些常用的图片数据集，如果你需要读取这些数据集，那么无需自己实现，只需要利用 Torchvision 就可以搞定。
    Torchvision 库就是常用数据集 + 常见网络模型 + 常用图像处理方法。
    Torchvision 中默认使用的图像加载器是 PIL

## 利用 Torchvision 读取数据

    Torchvision 库中的torchvision.datasets包中提供了丰富的图像数据集的接口。常用的图像数据集，例如 MNIST、COCO 等，这个模块都为我们做了相应的封装。
    下表中出了torchvision.datasets包所有支持的数据集。各个数据集的说明与接口，详见链接https://pytorch.org/vision/stable/datasets.html
    ![image.png](attachment:image.png)
    
    torchvision.datasets这个包本身并不包含数据集的文件本身，它的工作方式是
           * 先从网络上把数据集下载到用户指定目录，
           * 然后再用它的加载器把数据集加载到内存中。
           * 最后，把这个加载后的数据集作为对象返回给用户。
           
### MNIST 数据集简介

### 数据读取

In [12]:

# 以MNIST为例
import torchvision
mnist_dataset = torchvision.datasets.MNIST(root='./data',
                                       train=True,
                                       transform=None,
                                       target_transform=None,
                                       download=True)

100.0%


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



100.0%


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



100.0%


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



100.0%

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw




* root：是一个字符串，用于指定你想要保存 MNIST 数据集的位置。如果 download 是 Flase，则会从目标位置读取数据集；
* download：是布尔类型，表示是否下载数据集。如果为 True，则会自动从网上下载这个数据集，存储到 root 指定的位置。如果指定位置已经存在数据集文件，则不会重复下载；
* train：是布尔类型，表示是否加载训练集数据。如果为 True，则只加载训练数据。如果为 False，则只加载测试数据集。这里需要注意，并不是所有的数据集都做了训练集和测试集的划分，这个参数并不一定是有效参数，具体需要参考官方接口说明文档；
* transform：用于对图像进行预处理操作，例如数据增强、归一化、旋转或缩放等。这些操作我们会在下节课展开讲解；
* target_transform：用于对图像标签进行预处理操作。

In [18]:
type(torchvision.datasets.mnist.MNIST)

type

### 数据预览

In [19]:

mnist_dataset_list = list(mnist_dataset)
print(mnist_dataset_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [20]:

display(mnist_dataset_list[0][0])
print("Image label is:", mnist_dataset_list[0][1])

Image label is: 5


# 小结

* 两种读取数据的方法，也就是自定义和读取常用图像数据集。
* 最通用的数据读取方法，就是自己定义一个 Dataset 的派生类。而读取常用的图像数据集，就可以利用 PyTorch 提供的视觉包 Torchvision。
* torchvision.datasets继承了 Dataset 类，它在预定义许多常用的数据集的同时，还预留了数据预处理与数据增强的接口。
